version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET}
      JOOBLE_API_KEY: ${JOOBLE_API_KEY}
      API_URL: ${API_URL}
    env_file:
      - .env
    ports:
      - "${PORT}:3001"
    command: node server.js
    volumes:
      - .:/app/
      - /app/node_modules
      - /app/public/img/specializations

  postgres:
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
